const state = {
  mode: 'setup',
  daToken: null,
  githubUrl: '',
  githubToken: null,
  needsToken: false,
  org: '',
  repo: '',
  site: '',
  validating: false,
  repositoryValidated: false,
  blocks: [],
  selectedBlocks: new Set(),
  discovering: false,
  blocksDiscovered: false,
  libraryExists: false,
  showPagePicker: false,
  currentSite: '',
  pageSearchQuery: '',
  allPages: [],
  loadingPages: false,
  loadedFolders: {},
  pageSelections: {},
  processing: false,
  processStatus: {
    github: { org: '', repo: '', status: 'pending' },
    blocks: { total: 0, status: 'pending' },
    siteConfig: { status: 'pending', message: '' },
    blockDocs: { created: 0, total: 0, status: 'pending' },
    blocksJson: { status: 'pending', message: '' },
    errors: { count: 0, messages: [] },
    currentStep: '',
  },
  processResults: [],
  message: '',
  messageType: 'info',
};

export default state;
